# PyTorch Fundamentals Exercises




### 2. Create a random tensor with shape `(7, 7)`.


In [4]:
# Import torch
import torch

# Create random tensor
x = torch.rand((7,7))

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [7]:
# Create another random tensor
y = torch.rand((1,7))

# Perform matrix multiplication
torch.matmul(x, torch.transpose(y, 0, 1))

tensor([[1.2881],
        [1.8549],
        [0.9181],
        [1.2533],
        [2.1486],
        [1.7951],
        [1.8595]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [11]:
# Set manual seed
torch.manual_seed(0)


# Create two random tensors
x = torch.rand((7,7))
y = torch.rand((1,7))
# Matrix multiply tensors
res = torch.matmul(x, torch.transpose(y, 0, 1))
print(res, res.size())

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]]) torch.Size([7, 1])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [10]:
# Set random seed on the GPU
torch.manual_seed(1234)
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [15]:
# Set random seed
torch.cuda.manual_seed(1234)
torch.cuda.manual_seed(1234)
# Check for access to GPU
gpu_available = torch.cuda.is_available()
# Create two random tensors on GPU
if gpu_available:
  x = torch.rand((2,3)).to('cuda')
  y = torch.rand((2,3)).to('cuda')
  print(x)
  print(y)

tensor([[0.8102, 0.9801, 0.1147],
        [0.3168, 0.6965, 0.9143]], device='cuda:0')
tensor([[0.9351, 0.9412, 0.5995],
        [0.0652, 0.5460, 0.1872]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [16]:
# Perform matmul on tensor_A and tensor_B
res = torch.matmul(x, torch.transpose(y,0,1))
print(res)

tensor([[1.7488, 0.6094],
        [1.4999, 0.5721]], device='cuda:0')


### 8. Find the maximum and minimum values of the output of 7.

In [ ]:
# Find max

# Find min


### 9. Find the maximum and minimum index values of the output of 7.

In [21]:
# Find arg max
argmax = torch.argmax(res)
print(argmax)

# Find arg min
argmin = torch.argmin(res)
print(argmin)

tensor(0, device='cuda:0')
tensor(3, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [23]:
# Set seed
torch.manual_seed(7)

# Create random tensor
x = torch.rand((1,1,1,10))

# Remove single dimensions
y = torch.squeeze(x)

# Print out tensors and their shapes
print(x, x.size())
print(y, y.size())

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
